Repository zulip/zulip-desktop, pull requests merged in 2018-04, with the labels that each got.

#472 internal-links: open image link in webapp lightbox.
  app/renderer/js/preload.js
  app/renderer/js/utils/link-util.js
Labels: Type: Enhancement, size: S

#471 internal-links: open non-image links in hidden webview.
  app/renderer/css/main.css
  app/renderer/js/components/handle-external-link.js
  app/renderer/js/components/hidden-webview.js
  app/renderer/js/components/webview.js
  app/renderer/js/utils/link-util.js
Labels: size: L

#452 report-issue: Add report issue UX using send-feedback electron element.
  app/main/menu.js
  app/package-lock.json
  app/package.json
  app/renderer/css/main.css
  app/renderer/js/feedback.js
  app/renderer/js/main.js
  app/renderer/main.html
  package-lock.json
Labels: size: XL

#473 sidebar: Add scrollbar for list of organizations on overflow.
  app/renderer/css/main.css
  app/renderer/js/main.js
Labels: size: M

#475 snap: Update Snap configuration.
  snap/snapcraft.yaml
Labels: size: S
