Repository zulip/zulip-desktop, pull requests merged in 2018-09, with the labels that each got.

#552 readme: Add tray/dock integration to features.
  README.md
Labels: size: XS

#555 server-name: Unescape server name in window menu item.
  app/renderer/js/main.js
  app/renderer/js/utils/common-util.js
Labels: Type: Bug, size: M

#553 realm name: Update sidebar realm name when it's changed in webapp.
  app/main/index.js
  app/renderer/js/components/server-tab.js
  app/renderer/js/electron-bridge.js
  app/renderer/js/main.js
Labels: Priority: Low, Type: Enhancement, size: M

#529 Improve tray icon behavior
  app/main/index.js
  app/renderer/js/tray.js
Labels: size: S

#360 Add initial character of Realm Name instead of default icon
  app/renderer/css/main.css
  app/renderer/js/components/webview.js
  app/renderer/js/main.js
Labels: needs review, size: M

#560 Add dev into master
  app/package-lock.json
  app/package.json
  app/renderer/js/utils/config-util.js
  package-lock.json
  package.json
Labels: size: XL

#564 menubar: Auto hide menubar on Windows/Linux.
  app/main/index.js
  app/renderer/js/main.js
  app/renderer/js/pages/preference/general-section.js
Labels: Status: In Progress, Type: Enhancement, size: M

#568 menus: Rename a few menu items.
  app/main/menu.js
  app/renderer/js/tray.js
Labels: size: S

#572 Upgrade send feedback
  .gitattributes
  app/package-lock.json
  app/package.json
Labels: size: L
