Repository zulip/zulip-desktop, pull requests merged in 2018-03, with the labels that each got.

#435 Menu: Improve Help submenu
  app/main/menu.js
Labels: size: S

#437 il8n: Add a script that automatically creates locales from template.
  app/translations/bg.json
  app/translations/cs.json
  app/translations/de.json
  app/translations/en.json
  app/translations/es.json
  app/translations/fr.json
  app/translations/hi.json
  app/translations/hu.json
  app/translations/id.json
  app/translations/ja.json
  app/translations/ko.json
  app/translations/ml.json
  app/translations/nl.json
  app/translations/pl.json
  app/translations/pt.json
  app/translations/ru.json
  app/translations/sr.json
  app/translations/ta.json
  app/translations/tr.json
  package.json
  tools/fetch-pull-request.cmd
  tools/fetch-rebase-pull-request.cmd
  tools/locale-helper/index.js
  tools/locale-helper/locale-template.json
  tools/locale-helper/supported-locales.js
  tools/reinstall-node-modules
  tools/reinstall-node-modules.cmd
Labels: size: XL

#439 webview: Fix webview flickering.
  app/renderer/css/main.css
  app/renderer/js/components/webview.js
Labels: size: S

#446 design: Redesign Add new server page.
  app/main/index.js
  app/renderer/css/main.css
  app/renderer/css/preference.css
  app/renderer/js/main.js
  app/renderer/js/pages/preference/connected-org-section.js
  app/renderer/js/pages/preference/create-new-org.js
  app/renderer/js/pages/preference/nav.js
  app/renderer/js/pages/preference/new-server-form.js
  app/renderer/js/pages/preference/preference.js
  app/renderer/js/pages/preference/servers-section.js
Labels: size: XL

#441 add missing debian/ubuntu dependancy
  development.md
Labels: size: XS

#449 settings: Fix app settings overriding issue.
  app/renderer/js/main.js
Labels: Priority: High, size: S

#438 design: Improve existing organization design.
  app/renderer/css/preference.css
  app/renderer/js/pages/preference/new-server-form.js
  app/renderer/js/pages/preference/server-info-form.js
Labels: size: L

#458 Server page tweaks
  app/renderer/css/preference.css
  app/renderer/js/pages/preference/new-server-form.js
Labels: Priority: High, size: L

#460 "Organizations" settings page fixes and tweaks
  app/renderer/css/preference.css
  app/renderer/js/pages/preference/server-info-form.js
Labels: size: S

#454 Misc: Fix reinstall script for working across all platforms
  app/package-lock.json
  package.json
  tools/reinstall-node-modules.js
Labels: Priority: Low, Type: Bug, size: S

#461 org-settings: Responsive UI for connected orgs in smaller window sizes.
  app/renderer/css/preference.css
Labels: Priority: Medium, Type: Bug, size: S
