Repository zulip/zulip-desktop, pull requests merged in 2018-10, with the labels that each got.

#576 readme: Replace the word team with organizations.
  README.md
Labels: size: XS

#580 native-menus: Rename a few options of the submenus.
  app/main/menu.js
Labels: size: M

#567 about: Remove Found bug button.
  app/renderer/about.html
  app/renderer/css/about.css
Labels: size: S

#586 Disable beta updates if auto updates disabled
  app/renderer/js/pages/preference/general-section.js
Labels: needs more work
