Repository zulip/zulip-desktop, pull requests merged in 2018-12, with the labels that each got.

#605 domain-util: Include certificates in all requests for icon.
  app/renderer/js/utils/domain-util.js
Labels: Priority: Medium, Type: Bug, size: M

#616 Minimize to tray on startup.Fix issue #565
  app/main/index.js
  package-lock.json
Labels: size: XL

#612 Update electron to v3.0.10.
  app/main/index.js
  app/package-lock.json
  app/package.json
  app/renderer/js/main.js
  app/renderer/js/tray.js
  package-lock.json
  package.json
Labels: size: XL

#619 Add context menu to letter icon
  app/renderer/js/main.js
Labels: Type: Bug, size: L
