Repository zulip/zulip-desktop, pull requests merged in 2018-02, with the labels that each got.

#411 electron-connect: Disable electron-connect when it's ran from npm start.
  app/renderer/js/main.js
  app/renderer/main.html
  package.json
Labels: size: S

#413 design: Add back button.
  app/main/menu.js
  app/renderer/css/main.css
  app/renderer/js/main.js
  app/renderer/main.html
Labels: size: S

#420 activetab: Fix broken last active tab.
  app/main/index.js
  app/renderer/js/components/server-tab.js
  app/renderer/js/main.js
Labels: size: S

#408 updates: Pop a notification when a new update available.
  app/main/autoupdater.js
  app/main/linuxupdater.js
  app/package-lock.json
  app/package.json
  app/renderer/js/utils/linux-update-util.js
Labels: size: XL

#426 Only show the back button if it needed.
  app/renderer/css/main.css
  app/renderer/js/components/webview.js
  app/renderer/js/main.js
  app/renderer/main.html
Labels: needs review, size: M

#422 design: Not create a new instance of setting tab
  app/main/menu.js
  app/renderer/css/main.css
  app/renderer/js/components/functional-tab.js
  app/renderer/js/main.js
Labels: size: M

#429 fix: New organisation link overlapping existing servers.
  app/renderer/css/preference.css
Labels: size: XS
