Repository zulip/zulip-desktop, pull requests merged in 2018-05, with the labels that each got.

#483 internal-links: Download file attachment links using downloadURL.
  app/renderer/css/main.css
  app/renderer/js/components/handle-external-link.js
  app/renderer/js/components/hidden-webview.js
Labels: size: S

#478 feature: Add DND button in left sidebar.
  app/main/menu.js
  app/renderer/css/main.css
  app/renderer/js/main.js
  app/renderer/js/pages/preference/preference.js
  app/renderer/js/pages/preference/shortcuts-section.js
  app/renderer/js/utils/dnd-util.js
  app/renderer/main.html
Labels: Status: In Progress, Type: Enhancement, size: XL

#486 loading-indicator: Fix to hide loading indicator when server is loaded
  app/renderer/css/main.css
  app/renderer/js/components/webview.js
  app/renderer/js/main.js
Labels: Priority: Medium, Type: Bug, size: M

#487 menu: Add option to check for updates.
  app/main/autoupdater.js
  app/main/menu.js
Labels: Status: In Progress, Type: Enhancement, size: L

#493 setting: Add an option to disable the auto-updates.
  app/main/autoupdater.js
  app/main/index.js
  app/renderer/js/main.js
  app/renderer/js/pages/preference/general-section.js
Labels: size: M

#495 Update node modules.
  app/package-lock.json
  package-lock.json
  package.json
Labels: size: XL

#499 documentation: Change #electron stream links to #desktop stream link.
  CONTRIBUTING.md
Labels: size: XS
