Repository zulip/zulip-desktop, pull requests merged in 2018-08, with the labels that each got.

#516 electron-bridge: Implement electron bridge
  app/main/index.js
  app/renderer/js/electron-bridge.js
  app/renderer/js/main.js
  app/renderer/js/preload.js
Labels: Priority: Low, Type: Enhancement, size: L

#535 proxy: Set environment proxy variables as per proxyRules.
  app/main/linuxupdater.js
  app/renderer/js/utils/domain-util.js
  app/renderer/js/utils/proxy-util.js
Labels: Priority: High, Type: Enhancement, size: L

#546 settings: Update reference to toggle sidebar shortcut in general section
  app/renderer/js/pages/preference/general-section.js
Labels: size: XS

#549 pdf-viewer: Show pdf files in a new window.
  app/main/index.js
  app/renderer/js/components/handle-external-link.js
  app/renderer/js/utils/link-util.js
Labels: Type: Enhancement, size: M

#544 Update README.md.
  README.md
Labels: size: S
