Repository zulip/zulip-desktop, pull requests merged in 2018-07, with the labels that each got.

#508 config-files: Move all the configuration files into config folder.
  app/main/index.js
  app/main/menu.js
  app/renderer/js/utils/certificate-util.js
  app/renderer/js/utils/config-util.js
  app/renderer/js/utils/default-util.js
  app/renderer/js/utils/domain-util.js
  app/renderer/js/utils/linux-update-util.js
Labels: size: L

#511 package.json: Move adm dependecy to app/package.json
  app/package.json
  package.json
Labels: size: XS

#513 macOS: Add dock bouncing effect on macOS.
  app/renderer/js/components/webview.js
  app/renderer/js/main.js
  app/renderer/js/pages/preference/general-section.js
Labels: size: M

#514 Download file attachments to a default location.
  app/main/index.js
  app/renderer/css/preference.css
  app/renderer/js/components/handle-external-link.js
  app/renderer/js/main.js
  app/renderer/js/pages/preference/general-section.js
  app/resources/sounds/ding.ogg
Labels: size: L

#515 certificates: Make default option "No" on enter key press to reject certificate.
  app/renderer/js/utils/domain-util.js
Labels: size: XS

#525 fixes: Fix null of downloadPath when settings.json fails.
  app/renderer/js/pages/preference/general-section.js
Labels: size: XS

#521 files: Handle downloading files failure.
  app/main/index.js
  app/renderer/js/components/handle-external-link.js
Labels: size: M

#530 attachments: Fix failing attached file downloads.
  app/main/index.js
Labels: Priority: High, Type: Bug, size: XS
