Repository zulip/zulip-desktop, pull requests merged in 2019-06, with the labels that each got.

#666 Add option to hide menu bar to View menu
  app/main/index.js
  app/main/menu.js
  app/renderer/js/main.js
  app/renderer/js/pages/preference/preference.js
Labels: size: M

#674 Add loading indicator to sidebar
  app/renderer/css/main.css
  app/renderer/js/components/webview.js
  app/renderer/js/main.js
  app/renderer/main.html
Labels: size: L

#759 menu: Open help page of current active server.
  app/main/menu.js
  app/renderer/js/main.js
Labels: investigate, size: S

#765 typescript: Migrate components dir to typescript.
  app/package-lock.json
  app/renderer/js/components/tab.ts
  app/renderer/js/components/webview.ts
Labels: size: L

#768 components: Remove unused isLoading function from Tab.
  app/renderer/js/components/tab.js
Labels: size: XS

#752 spellchecker: Improve auto detection of spellchecker language.
  app/renderer/js/preload.js
  app/renderer/js/spellchecker.js
Labels: size: S

#774 typescript: Migrate main.js to typescript.
  app/renderer/js/main.ts
  package.json
Labels: size: XL

#775 tools: Add tools for running typescript compiler and electron app.
  package-lock.json
  package.json
  tools/run-dev
Labels: size: XL

#773 gulp: Add tasks for compile and run from src.
  gulpfile.js
  package-lock.json
  package.json
  tsconfig.json
Labels: size: XL

#779 typescript: Fix incorrect import statements.
  app/main/autoupdater.ts
  app/main/index.ts
  app/main/linuxupdater.ts
  app/main/menu.ts
  app/main/startup.ts
  app/renderer/js/components/tab.ts
  app/renderer/js/components/webview.ts
  app/renderer/js/electron-bridge.ts
  app/renderer/js/feedback.ts
  app/renderer/js/main.ts
  app/renderer/js/notification/darwin-notifications.ts
  app/renderer/js/notification/default-notification.ts
  app/renderer/js/notification/helpers.ts
  app/renderer/js/notification/index.ts
  app/renderer/js/pages/preference/add-certificate.ts
  app/renderer/js/pages/preference/base-section.ts
  app/renderer/js/pages/preference/general-section.ts
  app/renderer/js/pages/preference/network-section.ts
  app/renderer/js/tray.ts
  app/renderer/js/utils/certificate-util.ts
  app/renderer/js/utils/config-util.ts
  app/renderer/js/utils/default-util.ts
  app/renderer/js/utils/domain-util.ts
  app/renderer/js/utils/link-util.ts
  app/renderer/js/utils/linux-update-util.ts
  app/renderer/js/utils/logger-util.ts
  app/renderer/js/utils/proxy-util.ts
  app/renderer/js/utils/reconnect-util.ts
  app/renderer/js/utils/request-util.ts
  app/renderer/js/utils/sentry-util.ts
  app/renderer/js/utils/system-util.ts
  package-lock.json
  package.json
Labels: size: XL

#780 menu: Disable menu items on non-server pages.
  app/main/menu.js
Labels: size: S
