Repository zulip/zulip-desktop, pull requests merged in 2019-08, with the labels that each got.

#804 preference: Fix visually broken delete custom css button.
  app/renderer/css/preference.css
  app/renderer/js/pages/preference/general-section.ts
Labels: size: S

#806 docs: Add release notes for v4.0.0.
  changelog.md
Labels: size: S

#658 build: add msi to build targets
  package.json
Labels: size: S

#811 Remove trailing brackets from settings page.
  app/renderer/js/pages/preference/general-section.ts
Labels: size: XS

#808 Update ru.json
  app/translations/ru.json
Labels: size: L

#748 system-presence: Add ability to detect system presence.
  app/main/index.ts
  app/renderer/js/electron-bridge.ts
  app/renderer/js/main.ts
  app/renderer/js/preload.ts
Labels: size: L

#621 Fix flashing icons of servers in sidebar
  app/renderer/js/main.ts
Labels: size: S

#815 linux: Fix broken icon issue for snap package.
  package.json
Labels: size: XS
