Repository zulip/zulip-desktop, pull requests merged in 2019-07, with the labels that each got.

#783 reconnect-util: Gracefully reload current webview.
  app/renderer/js/utils/reconnect-util.js
Labels: size: XS

#785 Add missing transitive dependencies
  package.json
Labels: size: XS

#791 asar: Unpack node binding files.
  package.json
Labels: Priority: High, Type: Bug, size: XS

#755 dev: Use .env file for Sentry DSN.
  app/package.json
  app/renderer/js/utils/sentry-util.ts
  package-lock.json
  package.json
Labels: size: S

#795 docs: Add release notes for v3.1.0-beta.
  changelog.md
Labels: size: M

#796 Fix broken inline reply on macOS
  app/renderer/js/electron-bridge.ts
  app/renderer/js/notification/darwin-notifications.ts
Labels: Status: In Progress, Type: Bug, size: S

#757 sidebar: Sync loading indicator with loading GIF.
  app/renderer/js/components/webview.ts
  app/renderer/main.html
Labels: size: XS

#800 menu: Disable window sub-menu.
  app/main/menu.ts
Labels: Type: Enhancement, size: XS

#714 Revert to fallback icon only when needed
  app/renderer/js/utils/domain-util.ts
Labels: size: S

#802 Fix zoom shortcut
  app/main/menu.ts
  app/renderer/js/preload.ts
  package-lock.json
Labels: Type: Enhancement, blocked-upstream, size: L
