Repository zulip/zulip-desktop, pull requests merged in 2019-03, with the labels that each got.

#671 Fix broken link
  CONTRIBUTING.md
Labels: size: XS

#679 Default to starting app on login
  app/renderer/js/main.js
Labels: size: XS

#682 Update changelog.md
  changelog.md
Labels: size: S

#685 Allow insecure requests on user approval.
  app/renderer/js/utils/domain-util.js
Labels: size: M

#663 Switch to next server on Ctrl+Tab
  app/main/menu.js
  app/renderer/js/pages/preference/shortcuts-section.js
Labels: size: M

#688 Modify reset app data button
  app/renderer/css/preference.css
  app/renderer/js/pages/preference/general-section.js
Labels: size: S
