Repository zulip/zulip-desktop, pull requests merged in 2019-11, with the labels that each got.

#822 certificate: Make certificate location dynamic.
  app/renderer/js/utils/certificate-util.ts
  app/renderer/js/utils/request-util.ts
  app/translations/en-GB.json
Labels: size: XL

#834 macos: Enable notarization for macOS Catalina.
  build/entitlements.mac.plist
  package.json
  scripts/notarize.js
Labels: size: M

#841 docs: Add release notes for v4.0.2-beta.
  changelog.md
Labels: size: M

#845 Fix size of macOS dock icon.
  app/resources/Icon.icns
Labels: size: XS
