Repository zulip/zulip-desktop, pull requests merged in 2019-09, with the labels that each got.

#819 Reactivate network.js script.
  app/renderer/network.html
Labels: size: XS

#818 system-util: Set User-Agent from main process.
  app/main/index.ts
  app/renderer/js/utils/system-util.ts
Labels: size: S

#812 sidebar: Add option to open notification setting from the context menu.
  app/package-lock.json
  app/package.json
  app/renderer/js/components/webview.ts
  app/renderer/js/main.ts
  app/renderer/js/preload.ts
  package-lock.json
Labels: needs more work, size: XL

#824 sidebar: Improve UX for notification settings.
  app/renderer/js/main.ts
Labels: size: S

#821 Prompts Desktop App to ask for network setting before connecting first time
  app/renderer/css/preference.css
  app/renderer/js/main.ts
  app/renderer/js/pages/preference/new-server-form.ts
  app/translations/en-US.json
Labels: size: M
