Repository zulip/zulip-desktop, pull requests merged in 2019-05, with the labels that each got.

#729 logs: Limit the number of lines in log files.
  app/renderer/js/utils/logger-util.js
Labels: size: M

#734 focus: Fix focus after clicking back button.
  app/renderer/js/components/webview.js
Labels: size: XS

#735 menu: Remove minimize and close from File menu.
  app/main/menu.js
Labels: size: S

#736 Spellchecker: Enable spellcheck lang in server lang for all platform.
  app/renderer/js/spellchecker.js
Labels: size: S

#721 nsis: Allow install without admin previliges.
  package.json
Labels: size: XS

#732 settings: Add option to toggle Error Reporting.
  app/main/index.js
  app/renderer/js/main.js
  app/renderer/js/pages/preference/general-section.js
  app/renderer/js/utils/logger-util.js
  app/renderer/js/utils/proxy-util.js
Labels: Type: Question, size: M
