Repository zulip/zulip-desktop, pull requests merged in 2019-04, with the labels that each got.

#692 sidebar: Fixes to org cycling
  app/main/menu.js
Labels: Type: Bug, size: M

#643 add request options
  app/renderer/js/utils/domain-util.js
  app/renderer/js/utils/request-util.js
Labels: size: XL

#700 Fix text for Toggle DND in sidebar on hover
  app/renderer/js/main.js
Labels: size: XS

#656 sidebar and menu: add option to copy zulip url
  app/main/menu.js
  app/renderer/js/main.js
Labels: size: M

#698 webview: fix focus after soft reload
  app/renderer/js/components/webview.js
Labels: Type: Bug, size: XS

#639 webview: Work around buggy focus switching in Electron 3.0.10
  app/renderer/js/components/webview.js
Labels: investigate, size: S

#715 menu: Reorder file menu and add option to Add Organization.
  app/main/menu.js
  app/renderer/js/main.js
Labels: size: L

#722 Fix tip's place from bottom to top for Windows and Linux
  app/renderer/js/pages/preference/shortcuts-section.js
Labels: size: XS

#713 improve development guide
  development.md
Labels: size: XL

#717 shortcut: Allow zoom options from numpad.
  app/renderer/js/preload.js
Labels: Priority: Low, blocked-upstream, size: S

#699 lint: Implement CSS linting with stylelint
  .stylelintrc
  app/renderer/css/about.css
  app/renderer/css/main.css
  app/renderer/css/network.css
  app/renderer/css/preference.css
  app/renderer/css/preload.css
  package.json
Labels: size: XL

#725 Add "role" key to webview property.
  app/renderer/js/main.js
Labels: size: XS

#728 Unify case across menus and settings
  app/main/menu.js
  app/renderer/js/pages/preference/general-section.js
  app/renderer/js/pages/preference/shortcuts-section.js
Labels: size: S

#731 lint: Update css lint config to match zulip config.
  .stylelintrc
  app/renderer/css/about.css
  app/renderer/css/main.css
  app/renderer/css/network.css
  app/renderer/css/preference.css
Labels: size: XL

#726 lint: Implement HTML Linting with htmlhint and fix indent.
  .htmlhintrc
  app/renderer/about.html
  app/renderer/main.html
  app/renderer/network.html
  app/renderer/preference.html
  package.json
Labels: Type: Enhancement, size: XL
