Repository zulip/zulip-desktop, pull requests merged in 2020-01, with the labels that each got.

#858 Decode server name in Window menu.
  app/renderer/js/main.ts
Labels: size: XS

#829 Added option to select download locations.
  app/main/index.ts
  app/renderer/js/components/handle-external-link.ts
  app/renderer/js/main.ts
  app/renderer/js/pages/preference/general-section.ts
  app/translations/en.json
Labels: size: L

#859 startup: Use inbuilt electron API for autostartup.
  app/main/startup.ts
Labels: size: M
