Repository zulip/zulip-desktop, pull requests merged in 2020-03, with the labels that each got.

#882 appveyor.yml, .travis.yml: Test current Node.js releases
  .travis.yml
  appveyor.yml
Labels: size: S

#883 webview: Wait for dom-ready before sending messages
  app/renderer/js/components/webview.ts
  app/renderer/js/main.ts
Labels: size: S

#884 new-server-form: Remove useless .server-save-action wrappers
  app/renderer/js/pages/preference/new-server-form.ts
  tests/test-add-organization.js
Labels: size: S

#887 dependencies: Use one package.json structure
  .gitignore
  .travis.yml
  app/package-lock.json
  app/package.json
  package-lock.json
  package.json
  tools/reinstall-node-modules
  tools/reinstall-node-modules.cmd
  troubleshooting.md
  tsconfig.json
Labels: size: XL

#881 [WIP] Solve #878 Converting promise to async-await
  app/renderer/js/main.ts
  app/renderer/js/pages/preference/new-server-form.ts
  app/renderer/js/tray.ts
  app/renderer/js/utils/domain-util.ts
  app/renderer/js/utils/proxy-util.ts
  app/renderer/js/utils/reconnect-util.ts
  package.json
Labels: size: XL

#888 sentry-util: Hard-code the Sentry DSN.
  app/renderer/js/utils/sentry-util.ts
  package-lock.json
  package.json
Labels: size: S

#876 Update report issue placeholder.
  app/renderer/js/feedback.ts
Labels: size: S

#889 js: Explode singleton classes to modules
  app/renderer/js/pages/preference/badge-settings.ts
  app/renderer/js/utils/certificate-util.ts
  app/renderer/js/utils/common-util.ts
  app/renderer/js/utils/config-util.ts
  app/renderer/js/utils/domain-util.ts
  app/renderer/js/utils/enterprise-util.ts
  app/renderer/js/utils/link-util.ts
  app/renderer/js/utils/linux-update-util.ts
  app/renderer/js/utils/proxy-util.ts
  app/renderer/js/utils/request-util.ts
  app/renderer/js/utils/system-util.ts
  app/renderer/js/utils/translation-util.ts
  package.json
Labels: size: XL

#868 TS TODOs : makes reconnect-util generic, provides type annotations
  app/renderer/js/components/handle-external-link.ts
  app/renderer/js/notification/helpers.ts
  app/renderer/js/pages/preference/general-section.ts
  app/renderer/js/utils/proxy-util.ts
  app/renderer/js/utils/request-util.ts
Labels: size: S

#892 macOS: Replace deprecated isDarkMode() with shouldUseDarkColors.
  app/renderer/js/tray.ts
Labels: size: XS

#890 macOS: Fix undo redo not working on macOS.
  app/main/menu.ts
  app/renderer/js/main.ts
Labels: investigate, size: M
