Repository zulip/zulip-desktop, pull requests merged in 2020-04, with the labels that each got.

#909 tray: Work around Electron segfault on certain platforms
  app/renderer/js/tray.ts
Labels: size: XS

#919 dock: Do not toggle window on clicking dock.
  app/main/index.ts
Labels: Priority: High, investigate, size: XS

#927 scripts: Synchronize Debian scripts with electron-builder 22.4.1
  scripts/debian-add-repo.sh
  scripts/debian-uninstaller.sh
Labels: Type: Bug, linux, size: S

#894 macOS: Update dock icon.
  build/icon.icns
Labels: size: XS

#902 Add feature to set application language.
  app/renderer/css/preference.css
  app/renderer/js/pages/preference/base-section.ts
  app/renderer/js/pages/preference/general-section.ts
  app/renderer/js/utils/translation-util.ts
  app/translations/supported-locales.json
Labels: size: L

#938 server-icon: Handle server icon update gracefully.
  app/renderer/js/utils/domain-util.ts
Labels: size: S

#942 dependencies: Upgrade dependencies
  package-lock.json
  package.json
Labels: size: XL

#893 Fix #860 Refactor Code due to typescript migration
  app/renderer/js/components/functional-tab.ts
  app/renderer/js/components/server-tab.ts
  app/renderer/js/components/tab.ts
  app/renderer/js/components/webview.ts
  app/renderer/js/main.ts
  app/renderer/js/pages/preference/add-certificate.ts
  app/renderer/js/pages/preference/base-section.ts
  app/renderer/js/pages/preference/connected-org-section.ts
  app/renderer/js/pages/preference/find-accounts.ts
  app/renderer/js/pages/preference/general-section.ts
  app/renderer/js/pages/preference/nav.ts
  app/renderer/js/pages/preference/network-section.ts
  app/renderer/js/pages/preference/new-server-form.ts
  app/renderer/js/pages/preference/server-info-form.ts
  app/renderer/js/pages/preference/servers-section.ts
  app/renderer/js/pages/preference/shortcuts-section.ts
  app/renderer/js/utils/dnd-util.ts
  app/renderer/js/utils/domain-util.ts
Labels: size: XL

#929 Generate User-Agent when app starts, thus avoiding storing it on disk
  app/main/index.ts
  app/renderer/js/components/webview.ts
  app/renderer/js/main.ts
  app/renderer/js/utils/system-util.ts
Labels: size: M

#945 docs: Update changelog for release 5.1.0.
  changelog.md
Labels: size: S
