Repository zulip/zulip-desktop, pull requests merged in 2020-06, with the labels that each got.

#971 mac: Support pkg installer on macOS.
  package.json
Labels: size: XS

#974 translations: Prevent i18n to automatically add strings.
  app/renderer/js/utils/translation-util.ts
Labels: size: XS

#975 zoom: Fix zoom issues.
  app/main/menu.ts
Labels: size: XS

#972 windows: Turn off start at login by default.
  app/renderer/js/main.ts
Labels: size: M

#960 Docs: Update issue template.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Priority: Low, Type: Enhancement, size: L

#977 docs: Update issue template.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size: S

#967 spellchecker: Use Electron 8 built-in spellchecker.
  app/main/index.ts
  app/renderer/js/components/context-menu.ts
  app/renderer/js/components/webview.ts
  app/renderer/js/injected.ts
  app/renderer/js/main.ts
  app/renderer/js/pages/preference/general-section.ts
  app/renderer/js/preload.ts
  app/renderer/js/spellchecker.ts
  app/renderer/preference.html
  package-lock.json
  package.json
  typings.d.ts
Labels: size: XL

#980 Update electron to v8.3.3.
  package-lock.json
  package.json
Labels: size: L

#985 Update changelog for release v5.3.0.
  changelog.md
Labels: size: S

#989 Improve context-menu.
  app/renderer/js/components/context-menu.ts
Labels: Type: Enhancement, size: S

#990 context-menu: Remove trailing and leading separators when not required.
  app/renderer/js/components/context-menu.ts
Labels: size: S

#992 settings: Update font size for spellchecker explanation.
  app/renderer/css/preference.css
Labels: size: XS
