Repository zulip/zulip-desktop, pull requests merged in 2020-05, with the labels that each got.

#913 downloadFiles: Fix issue of showing two Save As dialog box.
  app/main/index.ts
  app/renderer/js/components/handle-external-link.ts
Labels: size: M

#943 electron-bridge: Add decrypt_clipboard helper (for browser-based social login)
  app/renderer/js/clipboard-decrypter.ts
  app/renderer/js/electron-bridge.ts
Labels: size: L

#950 help: Update Help Center URL.
  app/renderer/js/main.ts
Labels: investigate, size: XS

#951 CI: Clean unused steps from CI configuration
  .travis.yml
  appveyor.yml
  package.json
  scripts/travis-build-test.sh
  scripts/travis-xvfb.sh
Labels: size: M

#952 main: Turn electron-connect off by default
  app/renderer/js/main.ts
  gulpfile.js
Labels: size: S

#954 document: Remove inessential comment inherited from #902 and #909
  app/renderer/js/pages/preference/general-section.ts
Labels: size: XS

#961 mailmap: Add Git .mailmap for zulipchat.com → zulip.com
  .mailmap
Labels: size: XS

#962 Remove the insecure ignoreCerts option
  app/main/index.ts
  app/renderer/js/components/webview.ts
  app/renderer/js/main.ts
  app/renderer/js/utils/domain-util.ts
  app/renderer/js/utils/reconnect-util.ts
  app/renderer/js/utils/request-util.ts
  app/resources/messages.ts
Labels: size: XL

#941 macOS: Use electron API to get dark tray icon for the light theme.
  app/renderer/js/tray.ts
  app/resources/tray/light/trayosx.png
  app/resources/tray/light/trayosx@2x.png
  app/resources/tray/light/trayosx@3x.png
  app/resources/tray/light/trayosx@4x.png
  app/resources/tray/traymacOSTemplate.png
  app/resources/tray/traymacOSTemplate@2x.png
  app/resources/tray/traymacOSTemplate@3x.png
  app/resources/tray/traymacOSTemplate@4x.png
Labels: size: S

#924 Handle Reset options gracefully.
  app/main/menu.ts
  app/renderer/js/main.ts
  app/renderer/js/pages/preference/general-section.ts
Labels: size: XL

#964 window: Responsive fixes for main window.
  app/main/index.ts
  app/renderer/css/preference.css
Labels: Priority: Low, Type: Enhancement, size: S
